### ISSUE TITLE
The paper you followed

### ISSUE THREAD

**Issue by nmvbxcz** [andreybicalho/ExtendedMorphologicalProfiles#1]
hello, your code is perfect, but i would like to know which article you are referring to, thanks!

**Comment by andreybicalho** [comment]
Hi, thanks! 

Although they haven't used SVM, I believe the original idea is from J.A. Benediktsson, J.A. Palmason, and J.R. Sveinsson, “Classification of hyperspectral data from urban areas based on extended morphological profiles,” IEEE Trans. on Geoscience and Remote Sensing, vol. 43, no. 3, pp. 480–491, 2005.
