### ISSUE TITLE
Thank you 

### ISSUE THREAD

**Issue by px39n** [andreybicalho/ExtendedMorphologicalProfiles#3]
Thank you it is a good code. 
Do you know any similar open source code(EMPs)?  I'm curious how/where the authors implemented their method in papers.

**Comment by andreybicalho** [comment]
Thank you sir. Unfortunately I didn't find the original code of this method either. I tried my best at the time to reproduce their algorithm in the white paper. If you find any bug or mistake, please, feel free to submit a pull request.
